### ISSUE TITLE
I do not seem to be able to reimport theme from saved JSON file

### ISSUE THREAD

**Issue by chriscullen42** [ilikeprograms/Cluckles#25]
I have just used the site for the first time and I went through and changed a lot of the styles/colours etc then downloaded the CSS and JSON files to a local folder.

I have since gone back to the site and then clicked the Choose File button and selected the json file I downloaded earlier.  I then get an alert telling me to select a json file like the  one downloaded!

Any help would be appreciated as I do not want to go through that again!

I also do not appear to be able to upload the file into this message!  I wonder if it's a issue with Chrome under Windows 7 x64 pro.

**Comment by ilikeprograms** [comment]
Hey!

Have you tried it in some other browsers?
I can't look into right now as in still at work but later on I should be able to help.

If you really can't get the file import to work, you may be able to import it using the developer tools in chrome.

Which I could tell you how to do if you can get it to work in other browsers.

I hope you can get it working!

Tom

M: +44 (0)7428 759630
E: tom@ilikeprograms.com
Home Page: http://ilikeprograms.com
LinkedIn: http://uk.linkedin.com/in/ilikeprograms/

**Comment by ilikeprograms** [comment]
@chriscullen42 Have you taken a look at trying it in different browsers ?
I have been in Amsterdam all week with work so haven't had a chance to look into it for you.
I want to help get this issue resolved for you.

**Comment by chriscullen42** [comment]
I have tried Chrome and Firefox - both give the same alert message.  The file I use is the JSON file I downloaded from the editor - is that the correct file to use?

I will try on another machine running Windows 10 and see if that works!

Thanks for getting back to me with your suggestions so quickly.  I hope you enjoyed Amsterdam!

**Comment by chriscullen42** [comment]
Ok, so I used FireFox on windows 10.  Opened the clickles website, changed a few items (simple colour changes) and then downloaded the JSON and CSS files.  Then I closed the webpage, then went back into it, then tried to open the JSON or CSS file I had just downloaded and got the alert message "Please Select a JSON or Less file (like one exported from Cluckles)"

Not sure what else I can try.

**Comment by ilikeprograms** [comment]
Hmmm. Sounds like there may be a bug somewhere. Thanks for letting me know.
I will look into it tonight after work and see if I can figure it out.

I'm also slowly working towards replacing the website version with a desktop version of Cluckles.

Hopefully will work a lot better and hopefully support things other than Bootstrap

Anyway I will find out tonight what the problem is, and make sure you can get it to import!

Tom

M: +44 (0)7428 759630
E: tom@ilikeprograms.com
Home Page: http://ilikeprograms.com
LinkedIn: http://uk.linkedin.com/in/ilikeprograms/

**Comment by chriscullen42** [comment]
Thanks very much.  Would it help if I emailed the files I downloaded from the website for you to test with?  I do not appear to be able to upload them here!

**Comment by ilikeprograms** [comment]
Sure, why not.
Just so I can compare the output to what should be being output!

Tom

M: +44 (0)7428 759630
E: tom@ilikeprograms.com
Home Page: http://ilikeprograms.com
LinkedIn: http://uk.linkedin.com/in/ilikeprograms/

**Comment by ilikeprograms** [comment]
@chriscullen42 Just to make you aware, this issue is now fixed :)
